platform: x86

init:
  - git config --global core.autocrlf false

install:
  - git submodule update --init

build_script:
  - cmake .
  - cmake --build . --config Release

test_script:
  - git config alias.git '!git-git "$@"'
  - ps: CopyItem .\\Release\\git-git-%PLATFORM%.exe C:\\Windows -Force
  - ps: Import-Module .\\Pester\\Pester.psm1
  - ps: Invoke-Pester *.Tests.ps1
